### ISSUE TITLE
Intruder in the license

### ISSUE THREAD

**Issue by YawKar** [TobbyMax/Game#9]
There's an intruder in your license. I figured out that his name is "Aleksei Sultanov". I insist on removing him from the license.

**Comment by Pasha831** [comment]
I'm a bit sorry, but, in my humble opinion, so-called "Ruslan Talanov" is not an intruder at all. I would like to see some convincing arguments from your side to continue this conversation. But at this moment, there is nothing wrong with this license.

**Comment by DECAHTHUK** [comment]
I'm not dead, fu:(

**Comment by YawKar** [comment]
As sad as it is to say 😭, it's widely known that Aleksei Sultanov rests in peace. So he cannot be in the licence anymore because he lost his rights due to his lack of ability to live.

**Comment by Pasha831** [comment]
I am so sorry about the loss of such a great person. He was one of the best friends of mine: kind, intelligent, funny and dedicated man. I consider that it is our duty to immortalize the photo of a unique identity for future generations of software engineers.

**Comment by YawKar** [comment]
Great speech... Closing...
